### ISSUE TITLE
Toggle for character list

### ISSUE THREAD

**Issue by jcache** [jcache/evolition#6]
Should we toggle the view of the character list with the same button?

I think it would make it easy to view the details of the character and it seems like it is an intuitive assumption, but I'm not sure about the feel of it. Any thoughts?

**Comment by aestrro** [comment]
Yeah, it was like ^ before when I first deployed. I decided against it - as it gets pretty confusing handling the 'view' that is responsible for JUST opening it, or JUST closing it.
